export const baseUrl = 'https://yuanzhida.work:8000'
export const OSS_HOST = 'https://yuanzhida-cos-1352975306.cos.ap-beijing.myqcloud.com/'
export const api = {
  login: { url: '/api/answerly/v1/user/login', method: 'POST' },
  register: { url: '/api/answerly/v1/user', method: 'POST' },
  login_code: { url: '/api/answerly/v1/user/captcha' },
  register_code: { url: '/api/answerly/v1/user/send-code' },
  subjects: { url: '/api/answerly/v1/category' },
  questions: { url: '/api/answerly/v1/question/page' },
  newQuestion: { url: '/api/answerly/v1/question', method: 'POST' },
  oss_upload: { url: '/cos/upload' },
  register_code: { url: '/api/answerly/v1/user/send-code' },
  register: { url: '/api/answerly/v1/user', method: 'POST' },
  newAnswer: { url: '/api/answerly/v1/comment', method: 'POST' },
  questionDetail: { url: '/api/answerly/v1/question/' },
  comments: { url: '/api/answerly/v1/comment/page' },
  likeQuestion: { url: '/api/answerly/v1/question/like', method: 'POST' },
  likeComment: { url: '/api/answerly/v1/comment/like', method: 'POST' },
  checkLogin: { url: '/api/answerly/v1/user/check-login' },
  flagSolved: { url: '/api/answerly/v1/question/resolved', method: 'POST' },
  flagUseful: { url: '/api/answerly/v1/comment/useful', method: 'POST' },
  keywordSuggest: { url: '/api/answerly/v1/question/suggest' },
  deleteQuestion: { url: '/api/answerly/v1/question', method: 'DELETE' },
  correctQuestion: { url: '/api/answerly/v1/question', method: 'PUT' },
  deleteComment: { url: '/api/answerly/v1/comment', method: 'DELETE' },
  correctComment: { url: '/api/answerly/v1/comment', method: 'PUT' },
  historyQuestions: { url: '/api/answerly/v1/question/recent/page' },
  collectedQuestions: { url: '/api/answerly/v1/question/collect/my/page' },
  myComments: { url: '/api/answerly/v1/comment/my/page' },
  myQuestions: { url: '/api/answerly/v1/question/my/page' },
  sendResetPasswordCode: { url: '/api/answerly/v1/user/send-reset-password-code' },
  resetPassword: { url: '/api/answerly/v1/user/reset-password', method: 'POST' }
}